python3 src/alphaZero/conniption_zero/run.py main --game "hybrid alphazero ha.pkl"
python3 src/alphaZero/conniption_zero/run.py main --game "cells alphazero ca.pkl"
python3 src/alphaZero/conniption_zero/run.py main --game "sols alphazero sa.pkl"
python3 src/alphaZero/conniption_zero/run.py main --game "flip alphazero fa.pkl"
python3 src/alphaZero/conniption_zero/run.py main --game "random alphazero ra.pkl"
python3 src/alphaZero/conniption_zero/run.py main --game "qlearn alphazero qa.pkl"
python3 src/alphaZero/conniption_zero/run.py main --game "minimaxq alphazero ma.pkl"
