python3 src/alphaZero/conniption_zero/run.py main --game "alphazero hybrid ah.pkl"
python3 src/alphaZero/conniption_zero/run.py main --game "alphazero cells ac.pkl"
python3 src/alphaZero/conniption_zero/run.py main --game "alphazero sols as.pkl"
python3 src/alphaZero/conniption_zero/run.py main --game "alphazero flip af.pkl"
python3 src/alphaZero/conniption_zero/run.py main --game "alphazero random ar.pkl"
